// <auto-generated />
using System;
using Mastery.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mastery.Infrastructure.Migrations
{
    [DbContext(typeof(MasteryDbContext))]
    partial class MasteryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mastery.Domain.Entities.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("ActualEndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly?>("ExpectedEndDate")
                        .HasColumnType("date");

                    b.Property<int>("Intensity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Outcome")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("SuccessStatement")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("_focusGoalIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FocusGoalIds");

                    b.Property<string>("_focusRoleIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FocusRoleIds");

                    b.Property<string>("_nonNegotiables")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NonNegotiables");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "StartDate");

                    b.ToTable("Seasons", (string)null);
                });

            modelBuilder.Entity("Mastery.Domain.Entities.UserProfile.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("CurrentSeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("OnboardingVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("_roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Roles");

                    b.Property<string>("_values")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Values");

                    b.HasKey("Id");

                    b.HasIndex("CurrentSeasonId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("Mastery.Domain.Entities.UserProfile.UserProfile", b =>
                {
                    b.HasOne("Mastery.Domain.Entities.Season", "CurrentSeason")
                        .WithMany()
                        .HasForeignKey("CurrentSeasonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Mastery.Domain.Entities.UserProfile.Constraints", "Constraints", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BlockedTimeWindows")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("BlockedTimeWindows");

                            b1.Property<string>("ContentBoundaries")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ContentBoundaries");

                            b1.Property<string>("HealthNotes")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("HealthNotes");

                            b1.Property<int>("MaxPlannedMinutesWeekday")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(480)
                                .HasColumnName("MaxPlannedMinutesWeekday");

                            b1.Property<int>("MaxPlannedMinutesWeekend")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(240)
                                .HasColumnName("MaxPlannedMinutesWeekend");

                            b1.Property<string>("NoNotificationsWindows")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("NoNotificationsWindows");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("UserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.OwnsOne("Mastery.Domain.Entities.UserProfile.Preferences", "Preferences", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CoachingStyle")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("CoachingStyle");

                            b1.Property<string>("ExplanationVerbosity")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("ExplanationVerbosity");

                            b1.Property<string>("NotificationChannels")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("NotificationChannels");

                            b1.Property<string>("NudgeLevel")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("NudgeLevel");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("UserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");

                            b1.OwnsOne("Mastery.Domain.Entities.UserProfile.PlanningDefaults", "PlanningDefaults", b2 =>
                                {
                                    b2.Property<Guid>("PreferencesUserProfileId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<bool>("AutoScheduleHabits")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bit")
                                        .HasDefaultValue(true)
                                        .HasColumnName("AutoScheduleHabits");

                                    b2.Property<int>("BufferBetweenTasksMinutes")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasDefaultValue(5)
                                        .HasColumnName("BufferBetweenTasksMinutes");

                                    b2.Property<int>("DefaultTaskDurationMinutes")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasDefaultValue(30)
                                        .HasColumnName("DefaultTaskDurationMinutes");

                                    b2.HasKey("PreferencesUserProfileId");

                                    b2.ToTable("UserProfiles");

                                    b2.WithOwner()
                                        .HasForeignKey("PreferencesUserProfileId");
                                });

                            b1.OwnsOne("Mastery.Domain.Entities.UserProfile.PrivacySettings", "Privacy", b2 =>
                                {
                                    b2.Property<Guid>("PreferencesUserProfileId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<bool>("AllowAnonymousAnalytics")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bit")
                                        .HasDefaultValue(true)
                                        .HasColumnName("AllowAnonymousAnalytics");

                                    b2.Property<bool>("ShareProgressWithCoach")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bit")
                                        .HasDefaultValue(false)
                                        .HasColumnName("ShareProgressWithCoach");

                                    b2.HasKey("PreferencesUserProfileId");

                                    b2.ToTable("UserProfiles");

                                    b2.WithOwner()
                                        .HasForeignKey("PreferencesUserProfileId");
                                });

                            b1.OwnsOne("Mastery.Domain.ValueObjects.CheckInSchedule", "CheckInSchedule", b2 =>
                                {
                                    b2.Property<Guid>("PreferencesUserProfileId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<TimeOnly>("EveningTime")
                                        .HasColumnType("time")
                                        .HasColumnName("CheckInEveningTime");

                                    b2.Property<TimeOnly>("MorningTime")
                                        .HasColumnType("time")
                                        .HasColumnName("CheckInMorningTime");

                                    b2.HasKey("PreferencesUserProfileId");

                                    b2.ToTable("UserProfiles");

                                    b2.WithOwner()
                                        .HasForeignKey("PreferencesUserProfileId");
                                });

                            b1.Navigation("CheckInSchedule")
                                .IsRequired();

                            b1.Navigation("PlanningDefaults")
                                .IsRequired();

                            b1.Navigation("Privacy")
                                .IsRequired();
                        });

                    b.OwnsOne("Mastery.Domain.ValueObjects.Locale", "Locale", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Locale");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("UserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.OwnsOne("Mastery.Domain.ValueObjects.Timezone", "Timezone", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("IanaId")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Timezone");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("UserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.Navigation("Constraints")
                        .IsRequired();

                    b.Navigation("CurrentSeason");

                    b.Navigation("Locale")
                        .IsRequired();

                    b.Navigation("Preferences")
                        .IsRequired();

                    b.Navigation("Timezone")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
